name: Feature or Task
description: Plan a feature or task
body:
  - type: textarea
    attributes:
      label: Description
      description: Write a brief description of the task.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Purpose
      description: Describe the purpose of the task.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Possible approaches
      description: Describe possible approaches for the task.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Definition of done
      description: Write the definition of done for the task.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Dependencies
      description: Provide necessary dependencies if require (optional).
    validations:
      required: false

  - type: textarea
    attributes:
      label: Risks
      description: Specify any risks associated with the task (optional).
    validations:
      required: false
